name: Building GSI..

on: [push]

env:
  TZ: Asia/Kolkata
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect p7zip-full p7zip-rar
       
       - name: Clone my fork of Elementary Build system
         run: git clone https://github.com/JamieHoSzeYui/os
       
       - name: Build elementary 
         run: |
              cd os
              docker run --privileged -i -v /proc:/proc \
              -v ${PWD}:/working_dir \
              -w /working_dir \
              debian:latest \
              /bin/bash -s etc/terraform-daily-6.0-i386.conf < build.sh

       - name: Release Builds
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Weekly build Elementary"
          files: |
             os/builds/*/*
             
       - uses: actions/upload-artifact@v2
         with:
          name: Built ElementaryOS Image
          path: os/builds/*/*.iso
          
          
